services:
  web:
    image: silentdisco-web:offline
    build: ./web
    container_name: silentdisco-web
    network_mode: host
    environment:
      GROUP: ${GROUP:-239.255.0.1}
      PORT: ${PORT:-1234}
      # New: where udpxy runs (your router)
      UDPXY_HOST: ${UDPXY_HOST:-192.168.8.1}   # or 192.168.8.1
      UDPXY_PORT: ${UDPXY_PORT:-4022}
    volumes:
      - ./site:/opt/silentdisco/site:ro
      - ./webdata:/srv/http
    restart: unless-stopped

  streamer:
    image: silentdisco-streamer:offline
    build: ./streamer
    container_name: silentdisco-streamer
    network_mode: host
    user: "${UID}:${UID}"
    environment:
      GROUP: ${GROUP:-239.255.0.1}
      PORT: ${PORT:-1234}
      BITRATE: ${BITRATE:-192k}
      PULSE_SOURCE: ${PULSE_SOURCE:?set your PulseAudio source (e.g., MixxxMaster.monitor)}
      PULSE_SERVER: "unix:/run/user/${UID}/pulse/native"
      PULSE_COOKIE: /pulse-cookie
    volumes:
      - /run/user/${UID}/pulse:/run/user/${UID}/pulse
      - ${PULSE_COOKIE_PATH:-$HOME/.config/pulse/cookie}:/pulse-cookie:ro
    depends_on:
      - web
    restart: unless-stopped